library(readr)
library(dplyr)
library(lubridate)

#### Read input flow record ####
q_tt <- read_delim("Vermigliana_1996_1997.csv", delim=";", col_names = c("Date", "Monthly_flow"), col_types = "cd")
nq <- length(qtt[["Monthly_flow"]]) #length of the flow record
nq
i_efty <- 2
i_mvef <- 1
icons <- 1
rvmax	<- 20 * 10^6 #(10^6m3)
vrmin <- 1.5* 10^6 #(10^6m3)	
damhei <- 100 #(m)
power <- 0.1 * 10^6 #(MW)

#Spesifications
# write the spec options here
#maybe can do the optional eflow type etc with a function in the future

#Specifications:
#  Eflow_Type (variable name: i_efty)
#1: constant whole year
#2: variable on monthly basis
#3: proportional to input

#  Method_monthly_var_flows (variable name: i_mvef)
#1: VMF, 2014)
#2: Tessman, 1980
#3: Smakhtin et al., 2004
#4: Tennant, 1976
#5: Q90-QQ50, 2014

 # Parameters for reservoir volume restype: 
# 1: mainly consumptive water use
# 0: mainly non-consumptive water use
# vrmax: max storage volume
# vrmin: minimum storage volume
# damhei: dam height (max available head)
# power: power generated by the power plant

#### Pre-processing of inflows and downstream water uses ####
q_tt[["Date"]]<- mdy(q_tt[["Date"]])

q_tt <- q_tt%>%
  mutate(year= year(Date), 
         month=month(Date),
         day=day(Date))

MMF_tt <- q_tt %>% group_by(year, month) %>%
  summarise(mean_monthly_flow=mean(Monthly_flow))

MAF_tt <- q_tt %>% group_by(year) %>%
  summarise(mean_yearly_flow=mean(Monthly_flow))
  
ny <- nrow(MAF_tt)                               #number of years in the dataset
  

MMF <- MMF_tt %>% group_by(month) %>%           # Mean annual flow vector for the whole record
  summarise(month_average=mean(mean_monthly_flow))
  
MAF <- mean(MMF[["month_average"]])             # Mean annual flow
  
q50 <- q_tt %>% summarise(median = median(Monthly_flow))
q90 <- q_tt %>% summarise(ninetth_percentile = quantile(Monthly_flow, 0.10))
q97 <- q_tt %>% summarise(ninetyseventh_percentile = quantile(Monthly_flow, 0.03))

  
  
  
  
  




