setwd("C:/Local work folder/Leipzig workshop/from guido")

#install.packages(c("digest", "caTools", "bitops"))

#install.packages(c("readr", "dplyr", "lubridate","ggplot2","plotly","shiny"))
#tinytex::install_tinytex()

library(readr)
library(dplyr)
library(lubridate)
library(ggplot2)
library(plotly)


#### Read input flow record ####
q_tt <- read_delim("Vermigliana_1996_1997.csv", delim=";", col_names = c("Date", "Monthly_flow"), col_types = "cd")
nq <- length(q_tt[["Monthly_flow"]]) #length of the flow record
nq

i_efty <- 1 #Choose between 1-3 for the type of eflow method
#  Eflow_Type (variable name: i_efty)
#1: constant whole year
#2: variable on monthly basis
#3: proportional to input

i_mvef <- 5 #Choose between 1-5 scenarios
#1: VMF, 2014)
#2: Tessman, 1980
#3: Smakhtin et al., 2004
#4: Tennant, 1976
#5: Q90-QQ50, 201

icons <- 1
# Choose '1' for consumptive use and '0' for non-consumptive use 

rvmax	<- 20 * 10^6 #(10^6m3) #to keep it line with Guido's notations
rvmin <- 1.5* 10^6 #(10^6m3)	
damhei <- 100 #(m)
power <- 0.1 * 10^6 #(MW)


# Parameters for reservoir volume restype: 
# 1: mainly consumptive water use
# 0: mainly non-consumptive water use
# vrmax: max storage volume
# vrmin: minimum storage volume
# damhei: dam height (max available head)
# power: power generated by the power plant

#### Pre-processing of inflows and downstream water uses ####
q_tt[["Date"]]<- mdy(q_tt[["Date"]])

q_tt <- q_tt%>%
  mutate(year= year(Date), 
         month=month(Date),
         day=day(Date))

MMF_tt <- q_tt %>% group_by(year, month) %>%
  summarise(mean_monthly_flow=mean(Monthly_flow))

MAF_tt <- q_tt %>% group_by(year) %>%
  summarise(mean_yearly_flow=mean(Monthly_flow))

ny <- nrow(MAF_tt)                               #number of years in the dataset

MMF <- MMF_tt %>% group_by(month) %>%           # Mean annual flow vector for the whole record
  summarise(month_average=mean(mean_monthly_flow))

MAF <- mean(MMF[["month_average"]])             # Mean annual flow

#50, 90 and 97 % quantile calculation
q50 <- q_tt %>% summarise(fifty_percentile = quantile(Monthly_flow, 0.50))
q90 <- q_tt %>% summarise(ninetth_percentile = quantile(Monthly_flow, 0.10))
q97 <- q_tt %>% summarise(ninetyseventh_percentile = quantile(Monthly_flow, 0.03))

#### Eflow scenarios ####
qefm <-vector("numeric", 12)
LIHflo <- vector("numeric", 12)

if (i_efty==1){ #case 1:constant eflow throughout the whole year
  
  qefm <- as.numeric(rep(q90, 12))
  
} else if (i_efty==2){ #case 2: variable eflow on a monthly basis
  
  if (i_mvef==1){         # --------------- VMF (2014)
    for (i in 1:nrow(MMF)) {
      if (MMF[i, 2] <= 0.4*MAF) {
        qefm[i] <- (0.6*MAF)
        LIHflo[i] <- 1    #i denotes a low flow month
      } else if(MMF[i, 2] > 0.4*MAF && MMF[i, 2] <= 0.8*MAF) {
        qefm[i] <- as.numeric(0.45*MMF[i, 2]) #SK:I added as.numeric() here, otherwise it produces a list of different classes. There might be a more efficient solution like structruing the lists from the begining, but for now this works ok. 
        LIHflo[i] <- 2    #i denotes an intermediate flow month
      } else {
        qefm[i] <-(0.3*MAF)
        LIHflo[i] <- 3 #i denotes a high flow month
      }
    }
  } 
  else if (i_mvef==2){ # --------------- Tessmann (1980)
    for (i in 1:nrow(MMF)) {
      if (MMF[i, 2] <= 0.4*MAF) {
        qefm[i] <- as.numeric(MMF[i, 2]) #sk:see note above
        LIHflo[i] <- 1 #i denotes a low flow month
      } else if(MMF[i, 2] > 0.4*MAF && 0.4*MMF[i, 2] <= 0.4*MAF) {
        qefm[i] <- 0.4*MAF
        LIHflo[i] <- 2 #i denotes an intermediate flow month
      } else {
        qefm[i] <- 0.4*MAF
        LIHflo[i] <- 3 #i denotes a high flow month
      }
    } 
  } 
  else if (i_mvef==3) { #--------------- Smakhtin et al. (2004b)
    for (i in 1:nrow(MMF)) {
      if (MMF[i, 2] <= MAF) {
        qefm[i] <- q90[[1]] #sk:also for quantile data, instead of as.numeric, I just indicated the data to extract, need to test later on
        LIHflo[i] <- 1 #i denotes a low flow month
      } else {
        qefm[i] <- 0.2*MAF # check this rule
        LIHflo[i] <- 3 #i denotes a high flow month
      }
    } 
  } 
  else if (i_mvef==4) { #--------------- Tennant (1976)
    for (i in 1:nrow(MMF)) {
      if (MMF[i, 2] <= MAF) {
        qefm[i] <- 0.2*MAF
        LIHflo[i] <- 1 #i denotes a low flow month
      } else {
        qefm[i] <- 0.4*MAF
        LIHflo[i] <- 3 #i denotes a high flow month
      }
    } 
  } 
  else if (i_mvef==5) { #--------------- Q90-Q50 (2014)
    for (i in 1:nrow(MMF)) {
      if (MMF[i, 2] <= MAF) {
        qefm[i] <-q90[[1]]
        LIHflo[i] <- 1 #i denotes a low flow month
      } else {
        qefm[i] <- q50[[1]]
        LIHflo[i] <- 3 #i denotes a high flow month
      }
    }
  }
} else { #case 3
  #---------------- eflow proportional to the incoming flow -----------
  for (i in 1:nrow(MMF)) {
    if (MMF[i,2] < MAF) {
      qefm[i] <- q90[[1]]
      LIHflo[i] <- 1 #i denotes a low flow month
    } else {
      qefm[i] <- q50[[1]]
      LIHflo[i] <- 3 #i denotes a high flow month
    }
  }
}

qefm

#Conversion of monthly data to daily data
ndays <- c(31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31)
qefy <-vector("numeric", 365)
nsum <- 0
for (i in seq_along(ndays)){
  qefy[(nsum+1):(nsum+(ndays[i]))] <- rep(qefm[[i]], ndays[i])
  nsum <- ndays[i]+nsum
}

qef <- rep(qefy, ny) #GZ: Check for leap years
#SK: leap years is doable with lubridate package
qef <- c(qef[1:32], qef[32], qef[33:730])

#store all eflow scenarios
qef1 <- qef
qef21 <- qef 
qef22 <- qef
qef23 <- qef 
qef24 <- qef 
qef25 <- qef 
qef3 <- qef

eflows <- as.data.frame(cbind(qef1,qef21,qef22,qef23,qef24,qef25,qef3))
eflows$day <- seq(1, 731, by=1)


#### Reservoir operation module ####

##tests

#test1
#rvmax=rvmin=rvol
icons <- 1 

rvmax	<- 0 * 10^6 
rvmin <- 0 * 10^6

qef <- rep(0,nq)
alpha <- 0.8
beta <- 0.1
qcons <- alpha*q_tt[["Monthly_flow"]]
qncons <- beta*q_tt[["Monthly_flow"]]

#qcons <- rep(0,nq)
#qncons <- rep(0,nq)

#for testing
qhp <- power/damhei/9810           # average discharge (m3/s) for power production
#qcons <- rep(q90[[1,1]][1], nq)         # consumptive water use time series (m3/s) assumed as MAF
#qncons <- rep (qhp[1], nq)      # NON-consumptive water use time series (m3/s) based on input dam power
qspill <- rep(0,nq)
qdown <- rep(0,nq)
qout <- rep(0, nq)
qnet <- rep(0, nq)
unmdem <- 0
unmdays <- 0
rvol <- rep(0, nq)       # initialization
rvol[1] <- rvmax[1]/2        # initial reservoir volume 
dt <- 86400

num <- vector(mode="numeric", length = 731)
for (i in 1:(nq-1)){
  qdown[i] <- qspill[i]+icons*qef[i]+(1-icons)*max(qef[i], qncons[i])
  qout[i] <- qdown[i]+icons*qcons[i]
  qnet[i] <- q_tt[["Monthly_flow"]][i]-qout[i]
  rvol[i+1] <- rvol[i]+qnet[i]*dt
  if (rvol[i] >= rvmax[1]){
    qspill[i+1] <- (rvol[i]-rvmax[1])/dt
    rvol[i] <- rvmax[1]
    num[i] <- 1
  } else if (rvol[i]<rvmin[1]){
    unmdem <- unmdem+(qcons[i]*icons)+(qncons[i]*(1-icons)) # total unmet demand (consumpt + non consumpt)
    unmdays <- unmdays+1 # n. of days in which demand is unmet 
    qncons[i] <- 0
    qcons[i] <- 0
    rvol[i] <- rvmin[1]
    num[i] <- 2
  }
}


plot(x=(1:nq),rvol)
rvol


ggplot()+ geom_line(aes(x=(1:nq), y=q_tt[["Monthly_flow"]]), color="red")+
  geom_line(aes(x=(1:nq), y=qout), color="blue") +theme(legend.position="top") + 
   ylab( bquote("Flow ("~m^3~'/s)')) +  xlab("time (days)")

plot(x=q_tt[["Monthly_flow"]],y=qout)

qcheck <- (1-alpha)*q_tt[["Monthly_flow"]]
plot(x=qcheck,y=qout)


#test 2
#huge reservoir

rvmin <- 1.5* 10^6 #(10^6m3)
gamma_const <- 1
qsum <- sum(q_tt[["Monthly_flow"]])
rvmax <- gamma_const*qsum*86400

#for testing
qhp <- power/damhei/9810           # average discharge (m3/s) for power production
qcons <- rep(q90[[1,1]][1], nq)         # consumptive water use time series (m3/s) assumed as MAF
qncons <- rep (qhp[1], nq)
qspill <- rep(0,nq)
qdown <- rep(0,nq)
qout <- rep(0, nq)
qnet <- rep(0, nq)
unmdem <- 0
unmdays <- 0
rvol <- rep(0, nq)       # initialization
rvol[1] <- rvmax[1]/2        # initial reservoir volume 
dt <- 86400

num <- vector(mode="numeric", length = 731)
for (i in 1:(nq-1)){
  qdown[i] <- qspill[i]+icons*qef[i]+(1-icons)*max(qef[i], qncons[i])
  qout[i] <- qdown[i]+icons*qcons[i]
  qnet[i] <- q_tt[["Monthly_flow"]][i]-qout[i]
  rvol[i+1] <- rvol[i]+qnet[i]*dt
  if (rvol[i] >= rvmax[1]){
    qspill[i+1] <- (rvol[i]-rvmax[1])/dt
    rvol[i] <- rvmax[1]
    num[i] <- 1
  } else if (rvol[i]<rvmin[1]){
    unmdem <- unmdem+(qcons[i]*icons)+(qncons[i]*(1-icons)) # total unmet demand (consumpt + non consumpt)
    unmdays <- unmdays+1 # n. of days in which demand is unmet 
    qncons[i] <- 0
    qcons[i] <- 0
    rvol[i] <- rvmin[1]
    num[i] <- 2
  }
}


plot(x=(1:nq),rvol)
rvol
plot(x=(1:nq),qspill)
plot(x=(1:nq),q_tt[["Monthly_flow"]])

ggplot()+ geom_line(aes(x=(1:nq), y=q_tt[["Monthly_flow"]]), color="red")+
  geom_line(aes(x=(1:nq), y=qout), color="blue")
#############################################################


qhp <- power/damhei/9810           # average discharge (m3/s) for power production
qcons <- rep(q90[[1,1]][1], nq)         # consumptive water use time series (m3/s) assumed as MAF
qncons <- rep (qhp[1], nq)          # NON-consumptive water use time series (m3/s) based on input dam power
qspill <- rep(0,nq)
qdown <- rep(0,nq)
qout <- rep(0, nq)
qnet <- rep(0, nq)
unmdem <- 0
unmdays <- 0
rvol <- rep(0, nq)       # initialization
rvol[1] <- rvmax[1]/2        # initial reservoir volume 
dt <- 86400

#original code
num <- vector(mode="numeric", length = 731)
for (i in 1:(nq-1)){
  qdown[i] <- qspill[i]+icons*qef[i]+(1-icons)*max(qef[i], qncons[i])
  qout[i] <- qdown[i]+icons*qcons[i]
  qnet[i] <- q_tt[["Monthly_flow"]][i]-qout[i]
  rvol[i+1] <- rvol[i]+qnet[i]*dt
  if (rvol[i] >= rvmax[1]){
    qspill[i+1] <- (rvol[i]-rvmax[1])/dt
    rvol[i] <- rvmax[1]
    num[i] <- 1
  } else if (rvol[i]<rvmin[1]){
    unmdem <- unmdem+(qcons[i]*icons)+(qncons[i]*(1-icons)) # total unmet demand (consumpt + non consumpt)
    unmdays <- unmdays+1 # n. of days in which demand is unmet 
    qncons[i] <- 0
    qcons[i] <- 0
    rvol[i] <- rvmin[1]
    num[i] <- 2
  }
}

# SK alternative
#original code
num <- vector(mode="numeric", length = 731)
for (i in 1:(nq-1)){
  if (rvol[i] >= rvmax[1]){
    qspill[i] <- (rvol[i]-rvmax[1])/dt
    rvol[i] <- rvmax[1]
    num[i] <- 1
  } else if (rvol[i]<rvmin[1]){
    unmdem <- unmdem+(qcons[i]*icons)+(qncons[i]*(1-icons)) # total unmet demand (consumpt + non consumpt)
    unmdays <- unmdays+1 # n. of days in which demand is unmet 
    qncons[i] <- 0
    qcons[i] <- 0
    rvol[i] <- rvmin[1]
    num[i] <- 2
  }
  qdown[i] <- qspill[i]+icons*qef[i]+(1-icons)*max(qef[i], qncons[i])
  qout[i] <- qdown[i]+icons*qcons[i]
  qnet[i] <- q_tt[["Monthly_flow"]][i]-qout[i]
  rvol[i+1] <- rvol[i]+qnet[i]*dt
  
}

#test for qspill
#3
num <- vector(mode="numeric", length = 731)
for (i in 1:(nq-1)){
  if (rvol[i] >= rvmax[1]){
    qspill[i] <- (rvol[i]-rvmax[1])/dt
    rvol[i] <- rvmax[1] 
    num[i] <- 1
  } else if (rvol[i]<rvmin[1]){
    unmdem <- unmdem+(qcons[i]*icons)+(qncons[i]*(1-icons)) # total unmet demand (consumpt + non consumpt)
    unmdays <- unmdays+1 # n. of days in which demand is unmet 
    qncons[i] <- 0
    qcons[i] <- 0
    rvol[i] <- rvmin[1]
    num[i] <- 2
  }
  qdown[i] <- qspill[i]+icons*qef[i]+(1-icons)*max(qef[i], qncons[i])
  qout[i] <- qdown[i]+icons*qcons[i]
  qnet[i] <- q_tt[["Monthly_flow"]][i]-qout[i]
  rvol[i+1] <- rvol[i]+qnet[i]*dt
}


plot(x=(1:nq),y=rvol,ylim=c(0,20000000)) 

ggplot()+ geom_line(aes(x=(1:nq), y=q_tt[["Monthly_flow"]]), color="red")+
  geom_line(aes(x=(1:nq), y=qspill), color="blue")

ggplot()+ geom_line(aes(x=(1:nq), y=q_tt[["Monthly_flow"]]), color="red")+
  geom_line(aes(x=(1:nq), y=qnet), color="blue") +
  geom_line(aes(x=(1:nq), y=qout), color="green") +
  geom_line(aes(x=(1:nq), y=qdown), color="yellow") +
  geom_line(aes(x=(1:nq), y=qspill), color="pink")

plot(x=q_tt[["Monthly_flow"]],y=qspill) + abline (1,1)
rvmaxt <- rep(rvmax, nq)
plot(x=rvmaxt,y=rvol) + abline (1,1)
ggplot()+ geom_line(aes(x=(1:nq), y=rvmaxt), color="red")+
  geom_line(aes(x=(1:nq), y=rvol), color="blue")

#### Plotting ####
flow <- ggplot(q_tt,aes(Date, Monthly_flow)) +
  geom_line()+theme_bw()+ggtitle("Daily Discharge")
ggplotly(flow)

#all eflow scenarios plot 

library(tidyr)
plot_flow<- eflows %>%
  select(day,qef1,qef21,qef22,qef23,qef24,qef25,qef3) %>%
  gather(key = "variable", value = "value",-day)
head(plot_flow, 3)

eflows <- ggplot(plot_flow,aes(x=day, y=value))+
  geom_line(aes(color = variable, linetype = variable),size=1) +
  scale_color_brewer(palette="Paired") +
  theme_bw() +
  ggtitle(bquote('Eflow ' ~Q[ef]~'(t)')) + 
  xlab("time (days)") + ylab( bquote("Eflow ("~m^3~'/s)'))
eflows

# Calculated eflow plot
time_series <- ggplot()+ geom_line(aes(x=(1:nq), y=qef), color="green")+
  geom_line(aes(x=(1:nq), y=qncons), color="blue")+
  geom_line(aes(x=(1:nq), y=qcons), color="red")+
  theme_bw()+ ggtitle(bquote('Eflow ' ~Q[ef]~'(t)')) + xlab("time (days)") + ylab( bquote("Eflow ("~m^3~'/s)'))
time_series

# Reservoir volume
reservoir_volume <- ggplot() +
  geom_line(aes(x=(1:nq), rvol),color="blue")+theme_bw()+ggtitle("Reservoir Volume (t)") + 
  xlab("time (days)") + ylab( bquote("Res.Vol ("~m^3~')'))
reservoir_volume

# Outflow to the next dam
outflow_next_dam <- ggplot() +
  geom_line(aes(x=(1:nq), qdown),color="blue")+theme_bw()+ggtitle('Outflow to the next dam ' ~Q[down]~'(t)') + 
  xlab("time (days)") + ylab( bquote("Outflow ("~m^3~'/s)'))
outflow_next_dam

# Outflow to the next dam
excess_flow <- ggplot() +
  geom_line(aes(x=(1:nq), qspill),color="blue")+theme_bw()+ggtitle('Excess flow ' ~Q[spill]~'(t)') + 
  xlab("time (days)") + ylab( bquote("Excess flow ("~m^3~'/s)'))
excess_flow
